services:
  - type: web
    name: shortcut-shortcut
    env: static
    buildCommand: yarn build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x
    autoDeploy: true
